### ISSUE TITLE
Pads intersect with buttons

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-gamepad#10]
![photo_2019-07-12_13-37-59](https://user-images.githubusercontent.com/8670331/61122390-5c36c680-a4aa-11e9-9779-6d0408b05e35.jpg)

![photo_2019-07-12_13-39-26](https://user-images.githubusercontent.com/8670331/61122472-86888400-a4aa-11e9-9614-f77693dd2bb3.jpg)

**Comment by ibalashov24** [comment]
Pixel 2 XL (the same screen parameters)
![Screenshot_1563376205](https://user-images.githubusercontent.com/21558097/61387134-34869a80-a8be-11e9-8baa-18d266da4c51.png)
